### ISSUE TITLE
Setup?

### ISSUE THREAD

**Issue by DimitarCC** [kodi1/plugin.program.bscfusion#5]
How we can set up this in Kodi? It appears it is not anymore a program addon so after execution there is no more playlist downloaded so i cant setup the IPTV pvr.
Can you give more details about this?

**Comment by kodi1** [comment]
1. You need a tvheadend running.
2. Run ./map_to_hts.py [hts hostname/ip] [kodi hostname/ip]
3. Use Tvheadend PVR client addon for Kodi

**Comment by DimitarCC** [comment]
tvheadend requirement limit usage of this to any android box that is capable of running KODI! Why is this limitation coming?

**Comment by kodi1** [comment]
https://tvheadend.org/boards/5/topics/10286
