### ISSUE TITLE
Add optional username and password arguments to "map_to_hts.py" call.

### ISSUE THREAD

**Issue by yorgov** [kodi1/plugin.program.bscfusion#7]
Hello,
Could you please add the option to call the script with certain username and password when calling "./map_to_hts.py".

The issue I had was related with missing credentials when the script tries to access the TvHeadend server in order to register the channels.
My workaround was to hardcode the username and password right after getting the session using 
hts_conn.auth = ('user', 'pass')
Best Regards

**Comment by metost** [comment]
You can just call the script with ./map_to_hts.py **user:pass**@xx.xx.xx.xx yy.yy.yy.yy
